### ISSUE TITLE
Unresolved external link 

### ISSUE THREAD

**Issue by johnjohnsp1** [vxCrypt0r/Voidmaw#2]
Hi,
thanks for sharing the project, I get this error when I try to compile the code using Release instead of Debug on Studio 2022.

unresolved external symbol __imp_ZydisDecoderInit
#error directive: This header is specific to ARM targets
unresolved external symbol __imp_ZydisFormatterInit
unresolved external symbol __imp_ZydisDecoderDecodeFull
3 unresolved externals

confirmed with Debug mode I have no problem.
i have added the additional directories where the libs are stored

<img width="822" alt="Screenshot 2024-11-20 alle 14 43 52" src="https://github.com/user-attachments/assets/09fb85c7-ecb9-404f-88aa-fe542793b739">
<img width="825" alt="Screenshot 2024-11-20 alle 14 45 14" src="https://github.com/user-attachments/assets/726205de-9bea-48cf-9277-98f9c69cc69d">

**Comment by vxCrypt0r** [comment]
add the value ZYDIS_STATIC_BUILD to  Dismantle properties->C/C++->Preprocessor->Preprocessor Definitions
![2024-11-20 16_09_59-Clipboard](https://github.com/user-attachments/assets/b8f3add6-cd53-4205-9227-0196357fa0f9)

**Comment by johnjohnsp1** [comment]
worked, awesome thanks
